# -*- coding: utf-8 -*-
"""sql-query-generator-colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uACPDh8g4boJUETP0akLSeygChQFEsq

# Step 1 - Environment setup
"""

import torch

print("CUDA available:", torch.cuda.is_available())
print("GPU name:", torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")
print("VRAM:", round(torch.cuda.get_device_properties(0).total_memory / 1e9, 2), "GB" if torch.cuda.is_available() else "")

!pip install -q transformers datasets accelerate huggingface_hub

import os
os.kill(os.getpid(), 9)

import torch
from transformers import GPT2LMHeadModel, GPT2Tokenizer, Trainer, TrainingArguments, DataCollatorForLanguageModeling
from datasets import load_dataset
from huggingface_hub import login

print("torch version      :", torch.__version__)
print("CUDA available     :", torch.cuda.is_available())
print("transformers OK    : yes")
print("datasets OK        : yes")
print("huggingface_hub OK : yes")

login(token="huggingface_access_token")

"""# Step 2 - Load & explore data"""

from datasets import load_dataset

dataset = load_dataset("xlangai/spider")

print(dataset)

for i in range(3):
    example = dataset["train"][i]
    print(f"--- Example {i+1} ---")
    print("Question :", example["question"])
    print("SQL      :", example["query"])
    print("DB       :", example["db_id"])
    print()

print("Column names:", dataset["train"].column_names)
print()
print("Train size     :", len(dataset["train"]))
print("Validation size:", len(dataset["validation"]))

lengths = [len(ex["query"].split()) for ex in dataset["train"]]

print("Shortest SQL (words) :", min(lengths))
print("Longest SQL  (words) :", max(lengths))
print("Average SQL  (words) :", round(sum(lengths) / len(lengths), 1))

short  = sum(1 for l in lengths if l <= 10)
medium = sum(1 for l in lengths if 10 < l <= 30)
long_  = sum(1 for l in lengths if l > 30)

print()
print(f"Short  (<=10 words) : {short}  ({round(short/len(lengths)*100)}%)")
print(f"Medium (11-30 words): {medium} ({round(medium/len(lengths)*100)}%)")
print(f"Long   (>30 words)  : {long_}  ({round(long_/len(lengths)*100)}%)")

def format_example(example):
    return f"Question: {example['question']}\nSQL: {example['query']}"

for i in range(3):
    print(f"--- Formatted Example {i+1} ---")
    print(format_example(dataset["train"][i]))
    print()

"""# Step 3 - Preprocess & format"""

from transformers import GPT2Tokenizer

tokenizer = GPT2Tokenizer.from_pretrained("gpt2-medium")
tokenizer.pad_token = tokenizer.eos_token

print("Vocab size :", tokenizer.vocab_size)
print("Pad token  :", tokenizer.pad_token)

MAX_LENGTH = 128

def preprocess(example):
    text = f"Question: {example['question']}\nSQL: {example['query']}{tokenizer.eos_token}"
    tokenized = tokenizer(
        text,
        max_length=MAX_LENGTH,
        truncation=True,
        padding="max_length",
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

tokenized_dataset = dataset.map(
    preprocess,
    remove_columns=dataset["train"].column_names
)

print(tokenized_dataset)

sample = tokenized_dataset["train"][0]

print("Keys            :", list(sample.keys()))
print("input_ids length:", len(sample["input_ids"]))
print("labels length   :", len(sample["labels"]))
print()

decoded = tokenizer.decode(sample["input_ids"], skip_special_tokens=False)
print("Decoded sample:\n", decoded[:300])

tokenized_dataset.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

print("Train sample types:")
sample = tokenized_dataset["train"][0]
for k, v in sample.items():
    print(f"  {k}: {v.shape}, dtype={v.dtype}")

"""# Step 4 - Configure training"""

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./sql-gpt2-medium",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=100,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True,
)

print("Training config ready")
print(f"  Epochs          : {training_args.num_train_epochs}")
print(f"  Batch size      : {training_args.per_device_train_batch_size}")
print(f"  Warmup steps    : {training_args.warmup_steps}")
print(f"  FP16            : {training_args.fp16}")

from transformers import GPT2LMHeadModel, DataCollatorForLanguageModeling, Trainer

model = GPT2LMHeadModel.from_pretrained("gpt2-medium")
model.resize_token_embeddings(len(tokenizer))

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    data_collator=data_collator,
)

print("Model parameters:", round(model.num_parameters() / 1e6, 1), "M")
print("Trainer ready")

"""# Step 5 - Full fine-tune"""

trainer.train()

"""## Rerun with updated arguments for training"""

training_args = TrainingArguments(
    output_dir="./sql-gpt2-medium",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    warmup_steps=100,
    weight_decay=0.05,        # increased from 0.01
    logging_dir="./logs",
    logging_steps=50,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    fp16=True,
    learning_rate=1e-5,       # added — default 5e-5 is too aggressive
    max_grad_norm=0.5,        # added — clips large gradient updates
)

from transformers import GPT2LMHeadModel, DataCollatorForLanguageModeling, Trainer

model = GPT2LMHeadModel.from_pretrained("gpt2-medium")
model.resize_token_embeddings(len(tokenizer))

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    data_collator=data_collator,
)

print("Model parameters:", round(model.num_parameters() / 1e6, 1), "M")
print("Trainer ready")

trainer.train()

"""# Step 6 - Evaluate & test"""

import os

checkpoints = [d for d in os.listdir("./sql-gpt2-medium") if d.startswith("checkpoint")]
checkpoints.sort()
for c in checkpoints:
    print(c)

from transformers import GPT2LMHeadModel, GPT2Tokenizer

best_checkpoint = "./sql-gpt2-medium/checkpoint-875"  # replace with actual name

model = GPT2LMHeadModel.from_pretrained(best_checkpoint)
tokenizer = GPT2Tokenizer.from_pretrained("gpt2-medium")
tokenizer.pad_token = tokenizer.eos_token

model.eval()
print("Loaded checkpoint:", best_checkpoint)

import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
model = model.to(device)

def generate_sql(question, max_new_tokens=64):
    prompt = f"Question: {question}\nSQL:"
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
            do_sample=False,        # greedy decoding — deterministic output
            repetition_penalty=1.2  # penalizes repeating tokens
        )

    decoded = tokenizer.decode(outputs[0], skip_special_tokens=True)
    sql_part = decoded.split("SQL:")[-1].strip()
    return sql_part

# Test on a few questions
test_questions = [
    "How many singers are there?",
    "What is the average age of all singers?",
    "List all singer names ordered by age.",
]

for q in test_questions:
    print(f"Question : {q}")
    print(f"Generated: {generate_sql(q)}")
    print()

"""### Evaluation 1"""

correct = 0
total = 50

for i in range(total):
    example = dataset["validation"][i]
    generated = generate_sql(example["question"]).lower().strip()
    gold = example["query"].lower().strip()
    if generated == gold:
        correct += 1

print(f"Exact match accuracy: {correct}/{total} = {round(correct/total*100, 1)}%")

print("Sample predictions vs ground truth\n")
for i in range(5):
    example = dataset["validation"][i]
    generated = generate_sql(example["question"])
    print(f"Question : {example['question']}")
    print(f"Gold SQL : {example['query']}")
    print(f"Generated: {generated}")
    print()

"""### Evaluation 2"""

import re

def normalize_sql(sql):
    sql = sql.lower().strip()
    sql = re.sub(r'\s+', ' ', sql)        # collapse multiple spaces
    sql = sql.rstrip(';')                  # remove trailing semicolon
    return sql

correct = 0
total = 50

for i in range(total):
    example = dataset["validation"][i]
    generated = normalize_sql(generate_sql(example["question"]))
    gold = normalize_sql(example["query"])
    if generated == gold:
        correct += 1

print(f"Normalized exact match: {correct}/{total} = {round(correct/total*100, 1)}%")

print("Sample predictions vs ground truth\n")
for i in range(5):
    example = dataset["validation"][i]
    generated = generate_sql(example["question"])
    print(f"Question : {example['question']}")
    print(f"Gold SQL : {example['query']}")
    print(f"Generated: {generated}")
    print()

"""# Step 7 - Push to HF Hub"""

from huggingface_hub import HfApi

model_name = "gpt2-medium-sql-generator"  # will appear as your-username/gpt2-medium-sql-generator

model.push_to_hub(model_name)
tokenizer.push_to_hub(model_name)

print(f"Model pushed to: https://huggingface.co/poseidon1113/{model_name}")

from huggingface_hub import HfApi

api = HfApi()

model_card = """
---
language: en
tags:
- text-to-sql
- gpt2
- fine-tuned
- sql-generation
datasets:
- xlangai/spider
---

# GPT-2 Medium — SQL Query Generator

Fine-tuned GPT-2 Medium on the Spider text-to-SQL dataset to generate SQL queries from natural language questions.

## Training
- Base model: GPT-2 Medium (354M parameters)
- Dataset: Spider (7000 train / 1034 validation examples)
- Method: Full fine-tuning
- Best checkpoint: Epoch 1 (val loss 1.410)

## Usage
```python
from transformers import GPT2LMHeadModel, GPT2Tokenizer

model = GPT2LMHeadModel.from_pretrained("your-username/gpt2-medium-sql-generator")
tokenizer = GPT2Tokenizer.from_pretrained("your-username/gpt2-medium-sql-generator")

prompt = "Question: How many singers are there?\\nSQL:"
inputs = tokenizer(prompt, return_tensors="pt")
output = model.generate(**inputs, max_new_tokens=64)
print(tokenizer.decode(output[0], skip_special_tokens=True))
```

## Limitations
- GPT-2 is a small model — output SQL may hallucinate table/column names
- No schema awareness — works best on Singer/Concert domain from Spider training data
- Intended as a learning project demonstrating full fine-tuning pipeline
"""

api.upload_file(
    path_or_fileobj=model_card.encode(),
    path_in_repo="README.md",
    repo_id=f"poseidon1113/{model_name}",
    repo_type="model"
)

print("Model card uploaded")

